/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Report API liveness and LLM / detector / data availability.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scene
         * @description Base and zones.
         */
        get: operations["get_scene_api_scene_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Images
         * @description All frames sorted by capture time.
         */
        get: operations["list_images_api_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image File
         * @description Raw frame image (no filesystem paths leak to the client).
         */
        get: operations["get_image_file_api_images__image_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Analysis
         * @description Analyze one frame (reuses the latest result unless `force_refresh`).
         */
        post: operations["create_analysis_api_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Return a finished analysis.
         */
        get: operations["get_analysis_api_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description Start replaying ticks `start`..`end` in the background.
         */
        post: operations["create_run_api_watch_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Status, alerts and trackers of a run.
         */
        get: operations["get_run_api_watch_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/runs/{run_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Log
         * @description Every event so far (same objects as the SSE stream; also gives the UI typed events).
         */
        get: operations["get_log_api_watch_runs__run_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE: replay buffered events, then follow live until the run ends (heartbeat every 15 s).
         */
        get: operations["stream_events_api_watch_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recordings
         * @description Recorded runs available for demo replay (no LLM calls).
         */
        get: operations["get_recordings_api_watch_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recording
         * @description Every event of one recording, in order.
         */
        get: operations["get_recording_api_watch_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tracks
         * @description All tracks of the day with the frame each one belongs to.
         */
        get: operations["list_tracks_api_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description All field reports sorted by time, with parsed coordinates and zone.
         */
        get: operations["list_reports_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/motion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Track Motion
         * @description Motion of one track up to `at`, clamped to the track's time span.
         */
        get: operations["get_track_motion_api_tracks__track_id__motion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tuning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tuning View
         * @description Defaults, current values, overridden paths and prompt texts.
         */
        get: operations["get_tuning_view_api_admin_tuning_get"];
        /**
         * Put Tuning
         * @description Validate and save; applies to the next analysis and the next watch run.
         */
        put: operations["put_tuning_api_admin_tuning_put"];
        post?: never;
        /**
         * Reset Tuning
         * @description Back to the defaults.
         */
        delete: operations["reset_tuning_api_admin_tuning_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prompts/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Prompt Preview
         * @description Render a prompt text with sample scene values and the given tuning.
         */
        post: operations["post_prompt_preview_api_admin_prompts_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentKnobs
         * @description Agent settings; names match `Settings`, None = use the Settings value.
         */
        AgentKnobs: {
            /** Watcher Max Tool Calls */
            watcher_max_tool_calls: number | null;
            /** Supervisor Max Tool Calls */
            supervisor_max_tool_calls: number | null;
            /** Watcher Spot Checks */
            watcher_spot_checks: number | null;
            /** Watcher Reasoning Effort */
            watcher_reasoning_effort: ("low" | "high" | "max") | null;
            /** Supervisor Reasoning Effort */
            supervisor_reasoning_effort: ("low" | "high" | "max") | null;
            /** Brief Language */
            brief_language: ("tr" | "en") | null;
        };
        /**
         * AgentTraceEvent
         * @description Everything one agent turn saw and did: prompts, each LLM call (with the model's reasoning),
         *     each tool call and result, and the final output.
         */
        AgentTraceEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent_trace";
            /** Tick */
            tick: string;
            /** Agent */
            agent: string;
            /** Prompt File */
            prompt_file: string;
            /** System Prompt */
            system_prompt: string;
            /** User Message */
            user_message: string;
            /** Steps */
            steps: {
                [key: string]: unknown;
            }[];
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /**
             * Generated By
             * @enum {string}
             */
            generated_by: "llm" | "fallback";
            /** Duration Ms */
            duration_ms: number;
        };
        /**
         * AgentTuning
         * @description Everything the admin can tune.
         */
        AgentTuning: {
            behavior: components["schemas"]["BehaviorTuning"];
            groups: components["schemas"]["GroupTuning"];
            rubric: components["schemas"]["RubricTuning"];
            ceiling: components["schemas"]["CeilingTuning"];
            judgment: components["schemas"]["JudgmentTuning"];
            agents: components["schemas"]["AgentKnobs"];
            prompts: components["schemas"]["PromptOverrides"];
        };
        /**
         * Analysis
         * @description Everything the pipeline produced for one frame. Self-contained so it can be replayed.
         */
        Analysis: {
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            image: components["schemas"]["ImageMeta"] | null;
            scene: components["schemas"]["Scene"] | null;
            /** Steps */
            steps: components["schemas"]["StepResult"][];
            /** Detections */
            detections: components["schemas"]["Detection"][];
            /** Track Snapshots */
            track_snapshots: components["schemas"]["TrackSnapshot"][];
            /** Matches */
            matches: components["schemas"]["TrackMatch"][];
            /** Motions */
            motions: components["schemas"]["MotionProfile"][];
            /** Reports */
            reports: components["schemas"]["ReportClaim"][];
            /** Report Assessments */
            report_assessments: components["schemas"]["ReportAssessment"][];
            /** Risks */
            risks: components["schemas"]["VehicleRisk"][];
            brief: components["schemas"]["Brief"] | null;
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
            token_usage: components["schemas"]["TokenUsage"];
        };
        /**
         * AnalysisCreate
         * @description Request body for `POST /api/analyses`.
         */
        AnalysisCreate: {
            /** Image Id */
            image_id: string;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
        };
        /**
         * AnalysisCreated
         * @description Response of `POST /api/analyses`.
         */
        AnalysisCreated: {
            /** Analysis Id */
            analysis_id: string;
        };
        /**
         * Base
         * @description The protected base.
         */
        Base: {
            /** Name */
            name: string;
            position: components["schemas"]["LatLon"];
        };
        /**
         * BehaviorTuning
         * @description Route classification thresholds (services/behavior.behavior_class). Meters, degrees.
         */
        BehaviorTuning: {
            /** Parked Max Path M */
            parked_max_path_m: number;
            /** Leaving Start M */
            leaving_start_m: number;
            /** Leaving Gain M */
            leaving_gain_m: number;
            /** Loop Sweep Deg */
            loop_sweep_deg: number;
            /** Orbit Min Path M */
            orbit_min_path_m: number;
            /** Orbit Max Range M */
            orbit_max_range_m: number;
            /** Approach Gain M */
            approach_gain_m: number;
            /** Probe In M */
            probe_in_m: number;
            /** Probe Out M */
            probe_out_m: number;
            /** Probe Back M */
            probe_back_m: number;
            /** Probe Range M */
            probe_range_m: number;
            /** Stakeout Near M */
            stakeout_near_m: number;
            /** Stakeout Arrival M */
            stakeout_arrival_m: number;
            /** Stakeout Min */
            stakeout_min: number;
            /** Stop Step M */
            stop_step_m: number;
        };
        /**
         * Brief
         * @description Operator-facing risk brief for one frame.
         */
        Brief: {
            /** Image Id */
            image_id: string;
            /**
             * Level
             * @enum {string}
             */
            level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
            /** Vehicles */
            vehicles: components["schemas"]["VehicleBriefLine"][];
            /** Report Notes */
            report_notes: string[];
            /** Uncertainties */
            uncertainties: string[];
            /**
             * Recommended Action
             * @enum {string}
             */
            recommended_action: "MONITOR" | "VERIFY" | "ESCALATE";
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Generated By
             * @enum {string}
             */
            generated_by: "llm" | "fallback";
        };
        /**
         * CeilingTuning
         * @description Level ceiling rules (services/risk.level_ceiling). Meters, degrees, m/s, minutes.
         */
        CeilingTuning: {
            /** At Base M */
            at_base_m: number;
            /** Arrived From M */
            arrived_from_m: number;
            /** Pattern High M */
            pattern_high_m: number;
            /** Approach Heading Deg */
            approach_heading_deg: number;
            /** Approach High M */
            approach_high_m: number;
            /** Approach High Eta Min */
            approach_high_eta_min: number;
        };
        /**
         * ComponentStatus
         * @description Availability of one external dependency.
         */
        ComponentStatus: {
            /** Available */
            available: boolean;
            /** Detail */
            detail: string;
        };
        /**
         * Detection
         * @description One detected vehicle. Geo fields are filled by the georeference step.
         */
        Detection: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Center Px */
            center_px: [
                number,
                number
            ];
            position: components["schemas"]["LatLon"] | null;
            /** Distance To Base M */
            distance_to_base_m: number | null;
            /** Bearing From Base Deg */
            bearing_from_base_deg: number | null;
        };
        /**
         * EnvKnobs
         * @description Settings values used when an `AgentKnobs` field is None.
         */
        EnvKnobs: {
            /** Watcher Max Tool Calls */
            watcher_max_tool_calls: number;
            /** Supervisor Max Tool Calls */
            supervisor_max_tool_calls: number;
            /** Watcher Spot Checks */
            watcher_spot_checks: number;
            /**
             * Watcher Reasoning Effort
             * @enum {string}
             */
            watcher_reasoning_effort: "low" | "high" | "max";
            /**
             * Supervisor Reasoning Effort
             * @enum {string}
             */
            supervisor_reasoning_effort: "low" | "high" | "max";
            /**
             * Brief Language
             * @enum {string}
             */
            brief_language: "tr" | "en";
        };
        /**
         * ExpectedVehicle
         * @description A vehicle the human operator announced to the supervisor (trusted, unlike field reports).
         *     Code matches it to a track when one appears and keeps that vehicle LOW.
         */
        ExpectedVehicle: {
            /** Expected Id */
            expected_id: string;
            /** Announced At */
            announced_at: string;
            /** Description */
            description: string;
            /** Sector */
            sector: string;
            /** Arrive From */
            arrive_from: string;
            /** Arrive To */
            arrive_to: string;
            /** Vehicle Type */
            vehicle_type: string | null;
            /** Track Id */
            track_id: string | null;
        };
        /**
         * ExpectedVehicleEvent
         * @description An announced vehicle was registered, or matched to a track.
         */
        ExpectedVehicleEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "expected_vehicle";
            /** Tick */
            tick: string;
            vehicle: components["schemas"]["ExpectedVehicle"];
        };
        /**
         * FieldReport
         * @description One raw report from field_reports.json. `text` is untrusted.
         */
        FieldReport: {
            /** Report Id */
            report_id: string;
            /** Time */
            time: string;
            /** Time Min */
            time_min: number;
            /** Source */
            source: string;
            /** Text */
            text: string;
        };
        /** FrameAnalyzedEvent */
        FrameAnalyzedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "frame_analyzed";
            /** Tick */
            tick: string;
            /** Image Id */
            image_id: string;
            /** Sector */
            sector: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "detector_unavailable";
            /** Detections */
            detections: components["schemas"]["FrameDetection"][];
            /** Tracks In Frame */
            tracks_in_frame: string[];
            /** Note */
            note: string;
        };
        /**
         * FrameDetection
         * @description One detector box in a drone frame, georeferenced and matched to a track.
         */
        FrameDetection: {
            /** Detection Id */
            detection_id: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            position: components["schemas"]["LatLon"] | null;
            /** Track Id */
            track_id: string | null;
            /** Match M */
            match_m: number | null;
        };
        /**
         * GroupPattern
         * @description Vehicles in one watcher's area that behave together.
         */
        GroupPattern: {
            /** Track Ids */
            track_ids: string[];
            /** Description */
            description: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * GroupTuning
         * @description Moving-together thresholds (services/behavior.moving_groups). Meters.
         */
        GroupTuning: {
            /** Large Group */
            large_group: number;
            /** Group Radius M */
            group_radius_m: number;
            /** Group Min Move M */
            group_min_move_m: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness plus the state of every dependency with a fallback.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            llm: components["schemas"]["ComponentStatus"];
            detector: components["schemas"]["ComponentStatus"];
            data: components["schemas"]["ComponentStatus"];
        };
        /**
         * ImageMeta
         * @description One drone frame: size in pixels, capture time and ground corners.
         */
        ImageMeta: {
            /** Image Id */
            image_id: string;
            /** Width Px */
            width_px: number;
            /** Height Px */
            height_px: number;
            /** Capture Time */
            capture_time: string;
            /** Capture Min */
            capture_min: number;
            /** Corners */
            corners: {
                [key: string]: components["schemas"]["LatLon"];
            };
            /** Zone */
            zone: string | null;
        };
        /**
         * JudgmentTuning
         * @description Which watch rows go to the LLM in full (agent/watch/watcher.needs_judgment).
         */
        JudgmentTuning: {
            /** Closing Min M Per Min */
            closing_min_m_per_min: number;
        };
        /**
         * LatLon
         * @description WGS84 position in decimal degrees.
         */
        LatLon: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** LevelChangedEvent */
        LevelChangedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "level_changed";
            /** Tick */
            tick: string;
            /** Track Id */
            track_id: string;
            /**
             * From Level
             * @enum {string}
             */
            from_level: "LOW" | "MEDIUM" | "HIGH";
            /**
             * To Level
             * @enum {string}
             */
            to_level: "LOW" | "MEDIUM" | "HIGH";
            /** By */
            by: string;
            /** Pending */
            pending: boolean;
            /** Reason */
            reason: string;
        };
        /**
         * MapReport
         * @description A raw report placed on the field map: parsed coordinates and its zone.
         *
         *     `zone` is the zone the text names; otherwise the zone nearest its coordinates
         *     (`zone_named` tells which).
         */
        MapReport: {
            /** Report Id */
            report_id: string;
            /** Time */
            time: string;
            /** Time Min */
            time_min: number;
            /** Source */
            source: string;
            /** Text */
            text: string;
            location: components["schemas"]["LatLon"] | null;
            /** Zone */
            zone: string | null;
            /**
             * Zone Named
             * @default false
             */
            zone_named: boolean;
        };
        /**
         * MapTrack
         * @description A track for the field map, with the frame it belongs to (last point = capture time).
         */
        MapTrack: {
            /** Track Id */
            track_id: string;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
            /** Image Id */
            image_id: string | null;
        };
        /**
         * MotionProfile
         * @description Motion features of one track over the window before capture (AGENT_DESIGN §3 step 5).
         */
        MotionProfile: {
            /** Track Id */
            track_id: string;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
            /** Path Km */
            path_km: number;
            /** Mean Speed Ms */
            mean_speed_ms: number;
            /** Last10 Speed Ms */
            last10_speed_ms: number;
            /** Heading Deg */
            heading_deg: number | null;
            /** Bearing To Base Deg */
            bearing_to_base_deg: number;
            /** Dist Now M */
            dist_now_m: number;
            /** Dist 30M Ago M */
            dist_30m_ago_m: number | null;
            /** Dist 60M Ago M */
            dist_60m_ago_m: number | null;
            /** Min Dist M */
            min_dist_m: number;
            /** Approach Rate M Per Min */
            approach_rate_m_per_min: number;
            /** Stops */
            stops: components["schemas"]["Stop"][];
            /** Zones Visited */
            zones_visited: string[];
            /** Eta To Base Min */
            eta_to_base_min: number | null;
        };
        /**
         * OperatorAlert
         * @description The supervisor informing the human operator about a situation.
         */
        OperatorAlert: {
            /** Alert Id */
            alert_id: string;
            /** Tick */
            tick: string;
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "advisory" | "urgent" | "immediate";
            /** Track Ids */
            track_ids: string[];
            /** Headline */
            headline: string;
            /** Description */
            description: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** OperatorAlertEvent */
        OperatorAlertEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "operator_alert";
            /** Tick */
            tick: string;
            alert: components["schemas"]["OperatorAlert"];
        };
        /**
         * OperatorMessageEvent
         * @description The human operator wrote to the supervisor.
         */
        OperatorMessageEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "operator_message";
            /** Tick */
            tick: string;
            /** Time */
            time: string;
            /** Text */
            text: string;
        };
        /**
         * OperatorReplyEvent
         * @description The supervisor's answer to the operator, with what its tools did.
         */
        OperatorReplyEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "operator_reply";
            /** Tick */
            tick: string;
            /** Time */
            time: string;
            /**
             * Generated By
             * @enum {string}
             */
            generated_by: "llm" | "fallback";
            /** Duration Ms */
            duration_ms: number;
            /** Reply */
            reply: string;
            /** Actions */
            actions: components["schemas"]["SupervisorAction"][];
            /** Tool Calls */
            tool_calls: string[];
            /** Warnings */
            warnings: string[];
        };
        /**
         * PatternPoints
         * @description Rubric points for the danger patterns.
         */
        PatternPoints: {
            /** Loops Around Base */
            loops_around_base: number;
            /** Fixed Range Orbit */
            fixed_range_orbit: number;
            /** Probing Return */
            probing_return: number;
            /** Perimeter Stakeout */
            perimeter_stakeout: number;
        };
        /**
         * PromptOverrides
         * @description Admin prompt texts; None = the versioned .md file.
         */
        PromptOverrides: {
            /** Watcher */
            watcher: string | null;
            /** Supervisor */
            supervisor: string | null;
        };
        /**
         * PromptPreview
         * @description Rendered prompt with sample scene values, or the variable problems.
         */
        PromptPreview: {
            /** Rendered */
            rendered: string | null;
            /** Missing */
            missing: string[];
            /** Unknown */
            unknown: string[];
        };
        /**
         * PromptPreviewRequest
         * @description POST /api/admin/prompts/preview body.
         */
        PromptPreviewRequest: {
            /**
             * Name
             * @enum {string}
             */
            name: "watcher" | "supervisor";
            /** Text */
            text: string;
            tuning: components["schemas"]["AgentTuning"];
        };
        /**
         * PromptTexts
         * @description One text per prompt.
         */
        PromptTexts: {
            /** Watcher */
            watcher: string;
            /** Supervisor */
            supervisor: string;
        };
        /**
         * PromptVariables
         * @description Required `{{variables}}` per prompt.
         */
        PromptVariables: {
            /** Watcher */
            watcher: string[];
            /** Supervisor */
            supervisor: string[];
        };
        /**
         * ReportAssessment
         * @description Verdict on one report relative to one frame's own sensor data.
         */
        ReportAssessment: {
            /** Report Id */
            report_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "CORROBORATED" | "CONTRADICTED" | "UNVERIFIED" | "IRRELEVANT";
            /** Reason */
            reason: string;
            /** Checks */
            checks: components["schemas"]["ReportCheck"][];
            /** Linked Detection Ids */
            linked_detection_ids: string[];
            /** Trust Weight */
            trust_weight: number;
        };
        /**
         * ReportCheck
         * @description One code-side comparison of a claim against our own data.
         */
        ReportCheck: {
            /**
             * Name
             * @enum {string}
             */
            name: "location" | "presence" | "type" | "activity" | "instructions";
            /**
             * Status
             * @enum {string}
             */
            status: "match" | "mismatch" | "unknown";
            /** Detail */
            detail: string;
        };
        /**
         * ReportClaim
         * @description Structured claim extracted from one free-text report. The text is untrusted.
         */
        ReportClaim: {
            /** Report Id */
            report_id: string;
            /** Time */
            time: string;
            /** Time Min */
            time_min: number;
            /** Source */
            source: string;
            /** Text */
            text: string;
            location: components["schemas"]["LatLon"] | null;
            /** Zone */
            zone: string | null;
            /** Vehicle Type */
            vehicle_type: string | null;
            /** Count */
            count: number | null;
            /** Color */
            color: string | null;
            /**
             * Activity
             * @default unknown
             * @enum {string}
             */
            activity: "moving" | "stationary" | "loading" | "unknown";
            /**
             * Claim Kind
             * @default OTHER
             * @enum {string}
             */
            claim_kind: "SIGHTING" | "ALL_CLEAR" | "FRIENDLY_PRESENCE" | "TRAFFIC_NORMAL" | "OTHER";
            /**
             * Extracted By
             * @default rules
             * @enum {string}
             */
            extracted_by: "llm" | "rules";
        };
        /**
         * ReportJudgment
         * @description An agent's own judgment of one field report: does it fit our tracks, frames and the other
         *     reports? The verdict and the 0-100 credibility score are the model's; code only checks ids.
         */
        ReportJudgment: {
            /** Report Id */
            report_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "CONSISTENT" | "CONTRADICTED" | "UNVERIFIABLE" | "IRRELEVANT";
            /** Credibility */
            credibility: number;
            /** Reason */
            reason: string;
            /** Track Ids */
            track_ids: string[];
            /** Conflicts With */
            conflicts_with: string[];
            /**
             * Deception
             * @default false
             */
            deception: boolean;
        };
        /**
         * RiskFactor
         * @description One rubric line contributing points to a vehicle score.
         */
        RiskFactor: {
            /** Name */
            name: string;
            /** Points */
            points: number;
            /** Detail */
            detail: string;
        };
        /**
         * Rubric
         * @description Track-only rubric at a tick (no vehicle type or report points).
         */
        Rubric: {
            /** Score */
            score: number;
            /**
             * Level
             * @enum {string}
             */
            level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Factors */
            factors: components["schemas"]["RiskFactor"][];
        };
        /**
         * RubricTuning
         * @description Baseline risk rubric (services/risk). Meters, m/min, degrees, minutes, points.
         */
        RubricTuning: {
            /** Distance Tiers */
            distance_tiers: components["schemas"]["Tier"][];
            /** Approach Rate Tiers */
            approach_rate_tiers: components["schemas"]["Tier"][];
            /** Heading Points */
            heading_points: number;
            /** Heading Tolerance Deg */
            heading_tolerance_deg: number;
            /** Long Stop Min */
            long_stop_min: number;
            /** Stop Near Base M */
            stop_near_base_m: number;
            /** Stop Points First */
            stop_points_first: number;
            /** Stop Points Extra */
            stop_points_extra: number;
            pattern_points: components["schemas"]["PatternPoints"];
            /** Group Points */
            group_points: number;
            type_points: components["schemas"]["TypePoints"];
            /** Level Step */
            level_step: number;
        };
        /**
         * ScenarioLoadedEvent
         * @description A scripted demo scenario runs: its synthetic vehicles, so a client can draw them.
         */
        ScenarioLoadedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "scenario_loaded";
            /** Tick */
            tick: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Extra Tracks */
            extra_tracks: components["schemas"]["MapTrack"][];
        };
        /**
         * Scene
         * @description Static geography of the day: base plus zones.
         */
        Scene: {
            base: components["schemas"]["Base"];
            /** Zones */
            zones: components["schemas"]["Zone"][];
        };
        /**
         * StepResult
         * @description Final state of one pipeline step, stored in the analysis.
         */
        StepResult: {
            /**
             * Step
             * @enum {string}
             */
            step: "load_frame" | "detect" | "georeference" | "match_tracks" | "analyze_motion" | "assess_reports" | "score_risk" | "write_brief";
            /** Index */
            index: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "warning" | "error";
            /** Summary */
            summary: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: string[];
            /** Duration Ms */
            duration_ms: number | null;
        };
        /**
         * Stop
         * @description A run of samples with speed below the stop threshold.
         *
         *     `duration_min` counts 5-minute sample slots (k samples -> 5k min), matching the organizer's
         *     example (12:10..12:45 at one spot = "40 dk").
         */
        Stop: {
            /** Start */
            start: string;
            /** Duration Min */
            duration_min: number;
            position: components["schemas"]["LatLon"];
            /** Zone */
            zone: string | null;
            /** Distance To Base M */
            distance_to_base_m: number;
        };
        /**
         * SupervisorAction
         * @description One side-effecting tool call the supervisor made this tick.
         */
        SupervisorAction: {
            /** Tool */
            tool: string;
            /** Ok */
            ok: boolean;
            /** Summary */
            summary: string;
            /** Track Ids */
            track_ids: string[];
        };
        /**
         * SupervisorDecision
         * @description `submit_supervisor_decision` arguments.
         */
        SupervisorDecision: {
            /** Tick */
            tick: string;
            /** Situation Summary */
            situation_summary: string;
            /**
             * Threat Level
             * @enum {string}
             */
            threat_level: "LOW" | "MEDIUM" | "HIGH";
            /** Patterns */
            patterns: components["schemas"]["SupervisorPattern"][];
            /** Watch Next */
            watch_next: string[];
            /** Report Checks */
            report_checks: components["schemas"]["ReportJudgment"][];
        };
        /** SupervisorDecisionEvent */
        SupervisorDecisionEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "supervisor_decision";
            /** Tick */
            tick: string;
            /**
             * Generated By
             * @enum {string}
             */
            generated_by: "llm" | "fallback";
            /** Duration Ms */
            duration_ms: number;
            decision: components["schemas"]["SupervisorDecision"];
            /** Actions */
            actions: components["schemas"]["SupervisorAction"][];
            /** Tool Calls */
            tool_calls: string[];
            /** Warnings */
            warnings: string[];
            /** Reports */
            reports: components["schemas"]["FieldReport"][];
        };
        /**
         * SupervisorPattern
         * @description A pattern across vehicles, possibly across sectors.
         */
        SupervisorPattern: {
            /** Track Ids */
            track_ids: string[];
            /** Sectors */
            sectors: string[];
            /** Description */
            description: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * Suspicion
         * @description Why the supervisor dispatches a tracker or alerts the authorities.
         */
        Suspicion: {
            /** Hypothesis */
            hypothesis: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** What Would Clear It */
            what_would_clear_it: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
        };
        /** TickCompletedEvent */
        TickCompletedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tick_completed";
            /** Tick */
            tick: string;
            /** Duration Ms */
            duration_ms: number;
            /** Levels */
            levels: {
                [key: string]: number;
            };
        };
        /** TickStartedEvent */
        TickStartedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tick_started";
            /** Tick */
            tick: string;
            /** Active Vehicles */
            active_vehicles: number;
            /** Frames */
            frames: string[];
            /** Checks */
            checks: {
                [key: string]: string;
            };
        };
        /**
         * Tier
         * @description One rubric tier: `points` when the value passes `limit`.
         */
        Tier: {
            /** Limit */
            limit: number;
            /** Points */
            points: number;
        };
        /**
         * TokenUsage
         * @description LLM token counters for one analysis.
         */
        TokenUsage: {
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
        };
        /**
         * TrackMatch
         * @description Assignment of a detection to a track at capture time.
         */
        TrackMatch: {
            /** Detection Id */
            detection_id: string;
            /** Track Id */
            track_id: string | null;
            /** Distance M */
            distance_m: number | null;
            /** Second Best M */
            second_best_m: number | null;
            /** Second Best Track Id */
            second_best_track_id: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low" | "none";
        };
        /**
         * TrackPoint
         * @description One track sample.
         */
        TrackPoint: {
            /** Time */
            time: string;
            /** Time Min */
            time_min: number;
            position: components["schemas"]["LatLon"];
        };
        /**
         * TrackSnapshot
         * @description A track's interpolated position at capture time, if it falls inside the frame.
         */
        TrackSnapshot: {
            /** Track Id */
            track_id: string;
            position: components["schemas"]["LatLon"];
            /** Center Px */
            center_px: [
                number,
                number
            ];
            /** Matched Detection Id */
            matched_detection_id: string | null;
        };
        /**
         * TrackerState
         * @description A tracker assigned to one vehicle.
         */
        TrackerState: {
            /** Tracker Id */
            tracker_id: string;
            /** Track Id */
            track_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "FOLLOWING" | "LOST" | "RECALLED";
            /**
             * Source
             * @enum {string}
             */
            source: "REAL" | "SIMULATED";
            position: components["schemas"]["LatLon"];
            /** Dist To Base M */
            dist_to_base_m: number;
            /** Speed Ms */
            speed_ms: number;
            /** Heading Deg */
            heading_deg: number | null;
            /** Eta To Base Min */
            eta_to_base_min: number | null;
            /** Uncertainty M */
            uncertainty_m: number;
            /** Since */
            since: string;
            /** Last Tick */
            last_tick: string;
            suspicion: components["schemas"]["Suspicion"];
        };
        /** TrackerUpdateEvent */
        TrackerUpdateEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tracker_update";
            /** Tick */
            tick: string;
            tracker: components["schemas"]["TrackerState"];
        };
        /**
         * TuningView
         * @description GET/PUT/DELETE /api/admin/tuning response.
         */
        TuningView: {
            defaults: components["schemas"]["AgentTuning"];
            current: components["schemas"]["AgentTuning"];
            /** Overridden */
            overridden: string[];
            env_knobs: components["schemas"]["EnvKnobs"];
            prompt_defaults: components["schemas"]["PromptTexts"];
            prompt_variables: components["schemas"]["PromptVariables"];
            /** Hash */
            hash: string;
            /** Load Warning */
            load_warning: string | null;
        };
        /**
         * TypePoints
         * @description Rubric points by detected vehicle type (other types score 0).
         */
        TypePoints: {
            /** Truck */
            truck: number;
            /** Bus */
            bus: number;
            /** Van */
            van: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VehicleBriefLine
         * @description One sentence about one vehicle, with its evidence IDs.
         */
        VehicleBriefLine: {
            /** Detection Id */
            detection_id: string;
            /** Track Id */
            track_id: string | null;
            /**
             * Level
             * @enum {string}
             */
            level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Text */
            text: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * VehicleRisk
         * @description Rubric score (0-100) for one detected vehicle.
         */
        VehicleRisk: {
            /** Detection Id */
            detection_id: string;
            /** Track Id */
            track_id: string | null;
            /** Score */
            score: number;
            /**
             * Level
             * @enum {string}
             */
            level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Factors */
            factors: components["schemas"]["RiskFactor"][];
        };
        /**
         * VehicleRow
         * @description One vehicle in a sector at a tick; every number is computed by code.
         */
        VehicleRow: {
            /** Track Id */
            track_id: string;
            /** Vehicle Type */
            vehicle_type: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "new_in_sector" | "staying" | "new_track";
            position: components["schemas"]["LatLon"];
            /** Sector */
            sector: string;
            /** Dist To Base M */
            dist_to_base_m: number;
            /** Bearing From Base Deg */
            bearing_from_base_deg: number;
            /** Moving */
            moving: boolean;
            /** Speed Last10 Ms */
            speed_last10_ms: number;
            /** Heading Deg */
            heading_deg: number | null;
            /** Heading Vs Base Deg */
            heading_vs_base_deg: number | null;
            /** Approach Rate 60M M Per Min */
            approach_rate_60m_m_per_min: number;
            /** Closing Last5 M Per Min */
            closing_last5_m_per_min: number;
            /** Eta To Base Min */
            eta_to_base_min: number | null;
            /** Current Stop Min */
            current_stop_min: number;
            /** Long Stops Within 6Km */
            long_stops_within_6km: number;
            /**
             * Behavior Class
             * @enum {string}
             */
            behavior_class: "steady_approach" | "loops_around_base" | "fixed_range_orbit" | "probing_return" | "perimeter_stakeout" | "mixed_transit" | "leaving_base" | "parked" | "unknown";
            rubric: components["schemas"]["Rubric"];
            /**
             * Max Level
             * @default HIGH
             * @enum {string}
             */
            max_level: "LOW" | "MEDIUM" | "HIGH";
            /** Group Ids */
            group_ids: string[];
            /** Expected */
            expected: string | null;
            /**
             * Registry Level
             * @enum {string}
             */
            registry_level: "LOW" | "MEDIUM" | "HIGH";
            /** Pending Level */
            pending_level: ("LOW" | "MEDIUM" | "HIGH") | null;
            /** Notes Count */
            notes_count: number;
            /** One Liner */
            one_liner: string;
        };
        /**
         * VehicleVerdict
         * @description A watcher's level and reason for one vehicle.
         */
        VehicleVerdict: {
            /** Track Id */
            track_id: string;
            /**
             * Level
             * @enum {string}
             */
            level: "LOW" | "MEDIUM" | "HIGH";
            /** Reason */
            reason: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Note */
            note: string | null;
        };
        /** WarningEvent */
        WarningEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "warning";
            /** Tick */
            tick: string;
            /** Scope */
            scope: string;
            /** Message */
            message: string;
        };
        /**
         * WatchRecording
         * @description A recorded watch run available for demo replay.
         */
        WatchRecording: {
            /** Recording Id */
            recording_id: string;
            /** Ticks */
            ticks: string[];
            /** Watchers */
            watchers: string[];
            /** Events */
            events: number;
            /** Llm Turns */
            llm_turns: number;
            /** Alerts */
            alerts: number;
        };
        /**
         * WatchRunCreate
         * @description Request body for `POST /api/watch/runs` (times as HH:MM, both ticks included).
         */
        WatchRunCreate: {
            /**
             * Start
             * @default 13:50
             */
            start: string;
            /**
             * End
             * @default 14:15
             */
            end: string;
            /** Watchers */
            watchers?: number | null;
        };
        /**
         * WatchRunCreated
         * @description Response of `POST /api/watch/runs`.
         */
        WatchRunCreated: {
            /** Run Id */
            run_id: string;
        };
        /**
         * WatchRunStatus
         * @description State of one watch run.
         */
        WatchRunStatus: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "failed";
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Watchers */
            watchers: number;
            /** Events */
            events: number;
            /** Alerts */
            alerts: components["schemas"]["OperatorAlert"][];
            /** Trackers */
            trackers: components["schemas"]["TrackerState"][];
        };
        /**
         * WatcherReport
         * @description `submit_watch_report` arguments.
         */
        WatcherReport: {
            /** Tick */
            tick: string;
            /** Street State */
            street_state: string;
            /** Vehicles */
            vehicles: components["schemas"]["VehicleVerdict"][];
            /** Patterns */
            patterns: components["schemas"]["GroupPattern"][];
            /** Report Checks */
            report_checks: components["schemas"]["ReportJudgment"][];
        };
        /** WatcherReportEvent */
        WatcherReportEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "watcher_report";
            /** Tick */
            tick: string;
            /** Watcher */
            watcher: string;
            /** Sectors */
            sectors: string[];
            /**
             * Generated By
             * @enum {string}
             */
            generated_by: "llm" | "fallback";
            /** Duration Ms */
            duration_ms: number;
            /** Rows */
            rows: components["schemas"]["VehicleRow"][];
            report: components["schemas"]["WatcherReport"];
            /** Tool Calls */
            tool_calls: string[];
            /** Warnings */
            warnings: string[];
            /** Reports */
            reports: components["schemas"]["FieldReport"][];
        };
        /**
         * Zone
         * @description A monitored zone, identified by name (as used in reports).
         */
        Zone: {
            /** Name */
            name: string;
            center: components["schemas"]["LatLon"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_scene_api_scene_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scene"];
                };
            };
        };
    };
    list_images_api_images_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageMeta"][];
                };
            };
        };
    };
    get_image_file_api_images__image_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_watch_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_watch_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_api_watch_runs__run_id__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["TickStartedEvent"] | components["schemas"]["FrameAnalyzedEvent"] | components["schemas"]["AgentTraceEvent"] | components["schemas"]["ScenarioLoadedEvent"] | components["schemas"]["OperatorMessageEvent"] | components["schemas"]["OperatorReplyEvent"] | components["schemas"]["ExpectedVehicleEvent"] | components["schemas"]["WatcherReportEvent"] | components["schemas"]["LevelChangedEvent"] | components["schemas"]["SupervisorDecisionEvent"] | components["schemas"]["TrackerUpdateEvent"] | components["schemas"]["OperatorAlertEvent"] | components["schemas"]["WarningEvent"] | components["schemas"]["TickCompletedEvent"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_watch_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recordings_api_watch_recordings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchRecording"][];
                };
            };
        };
    };
    get_recording_api_watch_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["TickStartedEvent"] | components["schemas"]["FrameAnalyzedEvent"] | components["schemas"]["AgentTraceEvent"] | components["schemas"]["ScenarioLoadedEvent"] | components["schemas"]["OperatorMessageEvent"] | components["schemas"]["OperatorReplyEvent"] | components["schemas"]["ExpectedVehicleEvent"] | components["schemas"]["WatcherReportEvent"] | components["schemas"]["LevelChangedEvent"] | components["schemas"]["SupervisorDecisionEvent"] | components["schemas"]["TrackerUpdateEvent"] | components["schemas"]["OperatorAlertEvent"] | components["schemas"]["WarningEvent"] | components["schemas"]["TickCompletedEvent"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tracks_api_tracks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapTrack"][];
                };
            };
        };
    };
    list_reports_api_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapReport"][];
                };
            };
        };
    };
    get_track_motion_api_tracks__track_id__motion_get: {
        parameters: {
            query: {
                /** @description "HH:MM" */
                at: string;
            };
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotionProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tuning_view_api_admin_tuning_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuningView"];
                };
            };
        };
    };
    put_tuning_api_admin_tuning_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentTuning"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuningView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_tuning_api_admin_tuning_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuningView"];
                };
            };
        };
    };
    post_prompt_preview_api_admin_prompts_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
